# Generated by Django 2.1.4 on 2019-07-14 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20190714_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskToBePerformedBy',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 21, 46, 28, 303682)),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeOfAllocation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 21, 46, 28, 303682)),
        ),
    ]
