# Generated by Django 2.1.4 on 2019-07-14 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190714_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskToBePerformedBy',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 21, 47, 58, 450630)),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeOfAllocation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 21, 47, 58, 450630)),
        ),
    ]
